/* tslint:disable */
/* eslint-disable */
/*
Wikimedia

This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats.
### Global Rules
- Limit your clients to no more than 200 requests/s to this API.
  Each API endpoint's documentation may detail more specific usage limits.
- Set a unique `User-Agent` or `Api-User-Agent` header that
  allows us to contact you quickly. Email addresses or URLs
  of contact pages work well.

By using this API, you agree to Wikimedia's  [Terms of Use](https://wikimediafoundation.org/wiki/Terms_of_Use) and [Privacy Policy](https://wikimediafoundation.org/wiki/Privacy_policy). Unless otherwise specified in the endpoint documentation below, content accessed via this API is licensed under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)  and [GFDL](https://www.gnu.org/copyleft/fdl.html) licenses, and you irrevocably agree to release modifications or additions made through this API under these licenses.  See https://www.mediawiki.org/wiki/REST_API for background and details.
### Endpoint documentation
Please consult each endpoint's documentation for details on:
- Licensing information for the specific type of content
  and data served via the endpoint.
- Stability markers to inform you about development status and
  change policy, according to
  [our API version policy](https://www.mediawiki.org/wiki/API_versioning).
- Endpoint specific usage limits.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagecountsProject } from '../models';
// @ts-ignore
import { Problem } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * LegacyDataApi - axios parameter creator
 * @export
 */
export const LegacyDataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Given a project and a date range, returns a timeseries of pagecounts. You can filter by access site (mobile or desktop) and you can choose between monthly, daily and hourly granularity as well.  - Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental) - Rate limit: 100 req/s - License: Data accessible via this endpoint is available under the   [CC0 1.0 license](https://creativecommons.org/publicdomain/zero/1.0/). 
         * @param {string} project The name of any Wikimedia project formatted like {language code}.{project name}, for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped off. For projects like commons without language codes, use commons.wikimedia. 
         * @param {'all-sites' | 'desktop-site' | 'mobile-site'} accessSite If you want to filter by access site, use one of desktop-site or mobile-site. If you are interested in pagecounts regardless of access site use all-sites.
         * @param {'hourly' | 'daily' | 'monthly'} granularity The time unit for the response data. As of today, the supported granularities for this endpoint are hourly, daily and monthly. 
         * @param {string} start The timestamp of the first hour/day/month to include, in YYYYMMDDHH format.
         * @param {string} end The timestamp of the last hour/day/month to include, in YYYYMMDDHH format. In hourly and daily granularities this value is inclusive, in the monthly granularity this value is exclusive. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPagecountsAggregateByProjectAndDateRange: async (project: string, accessSite: 'all-sites' | 'desktop-site' | 'mobile-site', granularity: 'hourly' | 'daily' | 'monthly', start: string, end: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'project' is not null or undefined
            assertParamExists('getPagecountsAggregateByProjectAndDateRange', 'project', project)
            // verify required parameter 'accessSite' is not null or undefined
            assertParamExists('getPagecountsAggregateByProjectAndDateRange', 'accessSite', accessSite)
            // verify required parameter 'granularity' is not null or undefined
            assertParamExists('getPagecountsAggregateByProjectAndDateRange', 'granularity', granularity)
            // verify required parameter 'start' is not null or undefined
            assertParamExists('getPagecountsAggregateByProjectAndDateRange', 'start', start)
            // verify required parameter 'end' is not null or undefined
            assertParamExists('getPagecountsAggregateByProjectAndDateRange', 'end', end)
            const localVarPath = `/metrics/legacy/pagecounts/aggregate/{project}/{access-site}/{granularity}/{start}/{end}`
                .replace(`{${"project"}}`, encodeURIComponent(String(project !== undefined ? project : `-project-`)))
                .replace(`{${"access-site"}}`, encodeURIComponent(String(accessSite !== undefined ? accessSite : `-access-site-`)))
                .replace(`{${"granularity"}}`, encodeURIComponent(String(granularity !== undefined ? granularity : `-granularity-`)))
                .replace(`{${"start"}}`, encodeURIComponent(String(start !== undefined ? start : `-start-`)))
                .replace(`{${"end"}}`, encodeURIComponent(String(end !== undefined ? end : `-end-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/metrics/legacy/pagecounts/aggregate/{project}/{access-site}/{granularity}/{start}/{end}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LegacyDataApi - functional programming interface
 * @export
 */
export const LegacyDataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LegacyDataApiAxiosParamCreator(configuration)
    return {
        /**
         * Given a project and a date range, returns a timeseries of pagecounts. You can filter by access site (mobile or desktop) and you can choose between monthly, daily and hourly granularity as well.  - Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental) - Rate limit: 100 req/s - License: Data accessible via this endpoint is available under the   [CC0 1.0 license](https://creativecommons.org/publicdomain/zero/1.0/). 
         * @param {LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPagecountsAggregateByProjectAndDateRange(requestParameters: LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPagecountsAggregateByProjectAndDateRange(requestParameters.project, requestParameters.accessSite, requestParameters.granularity, requestParameters.start, requestParameters.end, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LegacyDataApi - factory interface
 * @export
 */
export const LegacyDataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LegacyDataApiFp(configuration)
    return {
        /**
         * Given a project and a date range, returns a timeseries of pagecounts. You can filter by access site (mobile or desktop) and you can choose between monthly, daily and hourly granularity as well.  - Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental) - Rate limit: 100 req/s - License: Data accessible via this endpoint is available under the   [CC0 1.0 license](https://creativecommons.org/publicdomain/zero/1.0/). 
         * @param {LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPagecountsAggregateByProjectAndDateRange(requestParameters: LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest, options?: AxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getPagecountsAggregateByProjectAndDateRange(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getPagecountsAggregateByProjectAndDateRange operation in LegacyDataApi.
 * @export
 * @interface LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest
 */
export type LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest = {
    
    /**
    * The name of any Wikimedia project formatted like {language code}.{project name}, for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped off. For projects like commons without language codes, use commons.wikimedia. 
    * @type {string}
    * @memberof LegacyDataApiGetPagecountsAggregateByProjectAndDateRange
    */
    readonly project: string
    
    /**
    * If you want to filter by access site, use one of desktop-site or mobile-site. If you are interested in pagecounts regardless of access site use all-sites.
    * @type {'all-sites' | 'desktop-site' | 'mobile-site'}
    * @memberof LegacyDataApiGetPagecountsAggregateByProjectAndDateRange
    */
    readonly accessSite: 'all-sites' | 'desktop-site' | 'mobile-site'
    
    /**
    * The time unit for the response data. As of today, the supported granularities for this endpoint are hourly, daily and monthly. 
    * @type {'hourly' | 'daily' | 'monthly'}
    * @memberof LegacyDataApiGetPagecountsAggregateByProjectAndDateRange
    */
    readonly granularity: 'hourly' | 'daily' | 'monthly'
    
    /**
    * The timestamp of the first hour/day/month to include, in YYYYMMDDHH format.
    * @type {string}
    * @memberof LegacyDataApiGetPagecountsAggregateByProjectAndDateRange
    */
    readonly start: string
    
    /**
    * The timestamp of the last hour/day/month to include, in YYYYMMDDHH format. In hourly and daily granularities this value is inclusive, in the monthly granularity this value is exclusive. 
    * @type {string}
    * @memberof LegacyDataApiGetPagecountsAggregateByProjectAndDateRange
    */
    readonly end: string
    
}

/**
 * LegacyDataApiGenerated - object-oriented interface
 * @export
 * @class LegacyDataApiGenerated
 * @extends {BaseAPI}
 */
export class LegacyDataApiGenerated extends BaseAPI {
    /**
     * Given a project and a date range, returns a timeseries of pagecounts. You can filter by access site (mobile or desktop) and you can choose between monthly, daily and hourly granularity as well.  - Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental) - Rate limit: 100 req/s - License: Data accessible via this endpoint is available under the   [CC0 1.0 license](https://creativecommons.org/publicdomain/zero/1.0/). 
     * @param {LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LegacyDataApiGenerated
     */
    public getPagecountsAggregateByProjectAndDateRange(requestParameters: LegacyDataApiGetPagecountsAggregateByProjectAndDateRangeRequest, options?: AxiosRequestConfig) {
        return LegacyDataApiFp(this.configuration).getPagecountsAggregateByProjectAndDateRange(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
