/*
Wikimedia

This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats.
### Global Rules
- Limit your clients to no more than 200 requests/s to this API.
  Each API endpoint's documentation may detail more specific usage limits.
- Set a unique `User-Agent` or `Api-User-Agent` header that
  allows us to contact you quickly. Email addresses or URLs
  of contact pages work well.

By using this API, you agree to Wikimedia's  [Terms of Use](https://wikimediafoundation.org/wiki/Terms_of_Use) and [Privacy Policy](https://wikimediafoundation.org/wiki/Privacy_policy). Unless otherwise specified in the endpoint documentation below, content accessed via this API is licensed under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)  and [GFDL](https://www.gnu.org/copyleft/fdl.html) licenses, and you irrevocably agree to release modifications or additions made through this API under these licenses.  See https://www.mediawiki.org/wiki/REST_API for background and details.
### Endpoint documentation
Please consult each endpoint's documentation for details on:
- Licensing information for the specific type of content
  and data served via the endpoint.
- Stability markers to inform you about development status and
  change policy, according to
  [our API version policy](https://www.mediawiki.org/wiki/API_versioning).
- Endpoint specific usage limits.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Originalimage } from './originalimage';
import { SummaryCoordinates } from './summary-coordinates';
import { Thumbnail } from './thumbnail';

/**
 * 
 * @export
 * @interface Summary
 */
export interface Summary {
    /**
     * The page title
     * @type {string}
     * @memberof Summary
     */
    'title': string;
    /**
     * Wikidata description for the page
     * @type {string}
     * @memberof Summary
     */
    'description'?: string;
    /**
     * 
     * @type {SummaryCoordinates}
     * @memberof Summary
     */
    'coordinates'?: SummaryCoordinates;
    /**
     * The page language direction code
     * @type {string}
     * @memberof Summary
     */
    'dir': string;
    /**
     * The page title how it should be shown to the user
     * @type {string}
     * @memberof Summary
     */
    'displaytitle'?: string;
    /**
     * First several sentences of an article in plain text
     * @type {string}
     * @memberof Summary
     */
    'extract': string;
    /**
     * First several sentences of an article in simple HTML format
     * @type {string}
     * @memberof Summary
     */
    'extract_html'?: string;
    /**
     * The page language code
     * @type {string}
     * @memberof Summary
     */
    'lang': string;
    /**
     * 
     * @type {Originalimage}
     * @memberof Summary
     */
    'originalimage'?: Originalimage;
    /**
     * The page ID
     * @type {number}
     * @memberof Summary
     */
    'pageid'?: number;
    /**
     * 
     * @type {Thumbnail}
     * @memberof Summary
     */
    'thumbnail'?: Thumbnail;
    /**
     * The time when the page was last editted in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format
     * @type {string}
     * @memberof Summary
     */
    'timestamp'?: string;
}

